version: '3'

services:
  pulseway:
    # build:
    #   context: ./build
    #   args:
    #     PULSEWAY_VERSION: 9.5.0
    image: jtmotox/pulseway:latest
    container_name: pulseway
    hostname: pulseway
    restart: always
    env_file: .env
    volumes:
      - ./config.xml:/etc/pulseway/config-template.xml:ro
